/* Components in components/ui and which of them have a docs page */

type UiComponent = {
  slug: string
  name: string
  documented?: boolean
}

export const uiComponents: UiComponent[] = [
  { slug: "accordion", name: "Accordion", documented: true },
  { slug: "alert", name: "Alert", documented: true },
  { slug: "alert-dialog", name: "Alert Dialog", documented: true },
  { slug: "aspect-ratio", name: "Aspect Ratio", documented: true },
  { slug: "attachment", name: "Attachment", documented: true },
  { slug: "avatar", name: "Avatar", documented: true },
  { slug: "badge", name: "Badge", documented: true },
  { slug: "breadcrumb", name: "Breadcrumb", documented: true },
  { slug: "bubble", name: "Bubble", documented: true },
  { slug: "button", name: "Button", documented: true },
  { slug: "button-group", name: "Button Group", documented: true },
  { slug: "calendar", name: "Calendar", documented: true },
  { slug: "card", name: "Card", documented: true },
  { slug: "carousel", name: "Carousel", documented: true },
  { slug: "chart", name: "Chart", documented: true },
  { slug: "checkbox", name: "Checkbox", documented: true },
  { slug: "collapsible", name: "Collapsible", documented: true },
  { slug: "combobox", name: "Combobox", documented: true },
  { slug: "command", name: "Command", documented: true },
  { slug: "context-menu", name: "Context Menu", documented: true },
  { slug: "dialog", name: "Dialog", documented: true },
  { slug: "direction", name: "Direction", documented: true },
  { slug: "drawer", name: "Drawer", documented: true },
  { slug: "dropdown-menu", name: "Dropdown Menu", documented: true },
  { slug: "empty", name: "Empty", documented: true },
  { slug: "field", name: "Field", documented: true },
  { slug: "hover-card", name: "Hover Card", documented: true },
  { slug: "input", name: "Input", documented: true },
  { slug: "input-group", name: "Input Group", documented: true },
  { slug: "input-otp", name: "Input OTP", documented: true },
  { slug: "item", name: "Item", documented: true },
  { slug: "kbd", name: "Kbd", documented: true },
  { slug: "label", name: "Label", documented: true },
  { slug: "loader", name: "Loader", documented: true },
  { slug: "marker", name: "Marker", documented: true },
  { slug: "menubar", name: "Menubar", documented: true },
  { slug: "message", name: "Message", documented: true },
  { slug: "message-scroller", name: "Message Scroller", documented: true },
  { slug: "native-select", name: "Native Select", documented: true },
  { slug: "navigation-menu", name: "Navigation Menu", documented: true },
  { slug: "pagination", name: "Pagination", documented: true },
  { slug: "popover", name: "Popover", documented: true },
  { slug: "progress", name: "Progress", documented: true },
  { slug: "questionnaire", name: "Questionnaire", documented: true },
  { slug: "radio-group", name: "Radio Group", documented: true },
  { slug: "resizable", name: "Resizable", documented: true },
  { slug: "scroll-area", name: "Scroll Area", documented: true },
  { slug: "select", name: "Select", documented: true },
  { slug: "separator", name: "Separator", documented: true },
  { slug: "sheet", name: "Sheet", documented: true },
  { slug: "sidebar", name: "Sidebar", documented: true },
  { slug: "skeleton", name: "Skeleton", documented: true },
  { slug: "slider", name: "Slider", documented: true },
  { slug: "spinner", name: "Spinner", documented: true },
  { slug: "switch", name: "Switch", documented: true },
  { slug: "table", name: "Table", documented: true },
  { slug: "tabs", name: "Tabs", documented: true },
  { slug: "textarea", name: "Textarea", documented: true },
  { slug: "toast", name: "Toast", documented: true },
  { slug: "toggle", name: "Toggle", documented: true },
  { slug: "toggle-group", name: "Toggle Group", documented: true },
  { slug: "tooltip", name: "Tooltip", documented: true },
]
